// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDsAQJam0thqEPoE-QZZH99p9AY98Xezc',
    appId: '1:318120846668:web:a75469e3547686127e1be9',
    messagingSenderId: '318120846668',
    projectId: 'accessijobs',
    authDomain: 'accessijobs.firebaseapp.com',
    storageBucket: 'accessijobs.firebasestorage.app',
    measurementId: 'G-S9XKSM3VGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvySfvTJsFydWCle0WNozgsmFyrnusOE',
    appId: '1:318120846668:android:5c54e96e9392ac127e1be9',
    messagingSenderId: '318120846668',
    projectId: 'accessijobs',
    storageBucket: 'accessijobs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIawNzJkzofufclLYXrrNydL25YEcV-I',
    appId: '1:318120846668:ios:777a3c88c278029c7e1be9',
    messagingSenderId: '318120846668',
    projectId: 'accessijobs',
    storageBucket: 'accessijobs.firebasestorage.app',
    androidClientId: '318120846668-5ejp4lsj34vrhikf01j04e1k9u2k7lvb.apps.googleusercontent.com',
    iosClientId: '318120846668-9nk5n5o7v9imn07107brp4rurfqtebek.apps.googleusercontent.com',
    iosBundleId: 'com.example.accessijobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIawNzJkzofufclLYXrrNydL25YEcV-I',
    appId: '1:318120846668:ios:777a3c88c278029c7e1be9',
    messagingSenderId: '318120846668',
    projectId: 'accessijobs',
    storageBucket: 'accessijobs.firebasestorage.app',
    androidClientId: '318120846668-5ejp4lsj34vrhikf01j04e1k9u2k7lvb.apps.googleusercontent.com',
    iosClientId: '318120846668-9nk5n5o7v9imn07107brp4rurfqtebek.apps.googleusercontent.com',
    iosBundleId: 'com.example.accessijobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDsAQJam0thqEPoE-QZZH99p9AY98Xezc',
    appId: '1:318120846668:web:b58aac3c0f2cab187e1be9',
    messagingSenderId: '318120846668',
    projectId: 'accessijobs',
    authDomain: 'accessijobs.firebaseapp.com',
    storageBucket: 'accessijobs.firebasestorage.app',
    measurementId: 'G-F5LNVHJYRB',
  );

}